### 登录
POST 127.0.0.1:9001/iiisunny/e-commerce/login
Content-Type: application/json

{
  "username": "xxx",
  "password": "xxx"
}

###
POST 127.0.0.1:9001/iiisunny/e-commerce/register
Content-Type: application/json

{
  "username": "xxx",
  "password": "xxx"
}
